security:
    encoders:
        App\Entity\User:
            algorithm: argon2i

    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false
            stateless: true

        main:
            pattern: ^/api
            fos_oauth: true
            stateless: true
            anonymous: false
            provider: app_user_provider

    access_control:
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }